### ISSUE TITLE
Support for Influx DB 1.x

### ISSUE THREAD

**Issue by bdf0506** [andresp/cablemodem-status#11]
The InfluxDBClient has [backwards compatibility](https://github.com/influxdata/influxdb-client-python#influxdb-1-8-api-compatibility) built in for Influx DB 1.x. However, if you are not using https on your InfluxDB instance, and you set `UseTls = False`, things still won't work since https is hardcoded into the code.

To workaround this, change the format of the URL in line 91 from this:
`influxUrl = "https://" + influxHost + ":" + influxPort`
to this:
`influxUrl = "http://" + influxHost + ":" + influxPort`

**Comment by andyp-79** [comment]
Thanks for reporting the issue. This issue has been fixed.
